### ISSUE TITLE
fix up the json callback

### ISSUE THREAD

**Issue by awangg** [waytab/manage#1]
1. the actual bell-schedule in our config.json, which our time.js file is really built for, differentiates between bell 1, 2, 3, and 4 (weekend) schedules as like subarrays. this one doesn't, so the getCurrentBlock() function in time.js gets confused af. should fix, you could probably copy the getTodaySchedule() function in time.js to create the subproperty.
2. There should be a length property in the json callback.

YEET

**Comment by awangg** [comment]
you did it wrong

**Comment by awangg** [comment]
![screen shot 2018-12-09 at 7 15 53 pm](https://user-images.githubusercontent.com/26381500/49704900-ea7e5d80-fbe6-11e8-9559-a7725dfe405a.png)
was testing special schedule for another commit in the main repository when i found out that the call wasn't actually returning a schedule

**Comment by awangg** [comment]
![screen shot 2018-12-09 at 7 16 45 pm](https://user-images.githubusercontent.com/26381500/49704909-fe29c400-fbe6-11e8-87c3-f2f4bd521034.png)
this is the data i inputted

**Comment by awangg** [comment]
also special schedules for the day of still show up as in the past. for example, i tested a special schedule for today (12/9) and it was like "lol nope it was a past schedule" then didn't show up in waytab. but it does load the special schedule for 12/10...

**Comment by awangg** [comment]
https://github.com/waytab/WayTab/commit/9cd7b87c276be55f9ea65e6640ec6ee8c15006e0 don't bother adding a length thing

**Comment by andrewward2001** [comment]
right so the thing with the schedule showing but no periods was me being a buffoon but i fixed it (always check your code kids) https://github.com/waytab/manage/commit/2c1a4e54a2b1404aa4a4ba39affb36ae53ae2f71

> also special schedules for the day of still show up as in the past. for example, i tested a special schedule for today (12/9) and it was like "lol nope it was a past schedule" then didn't show up in waytab. but it does load the special schedule for 12/10...

ya so the server time is different so in the interface itll say its in the past but if you supply the timestamp in the ajax call itll be correct, we went over this at least twice

**Comment by andrewward2001** [comment]
and also the entire database row of the individual period will be outputted in the ajax so just ignore the id and schedule fields on the individual periods

**Comment by awangg** [comment]
> ya so the server time is different so in the interface itll say its in the past but if you supply the timestamp in the ajax call itll be correct, we went over this at least twice

ur mean
